### ISSUE TITLE
Activadores no aparecen

### ISSUE THREAD

**Issue by iroblero** [pfelipm/importadorplus#2]
Hola! Me funciona súper la plantilla, el único problema es que en la sección de Herramientas no me da acceso a los Activadores, a que puede deberse?

![image](https://user-images.githubusercontent.com/130387754/230943374-05071bab-18fe-4827-ab49-ba5a66261ff4.png)

**Comment by pfelipm** [comment]
Esta plantilla ya tiene unos años y tanto el editor de hojas de cálculo de Google como el IDE de desarrollo han cambiado.

Para acceder al panel de activadores ahora tienes que hacer esto:

1.  `Extensiones` **→ ** `Apps Script.`
2.  Clic en la opción `⏰ Activadores` del menú del panel lateral izquierdo.

![](https://user-images.githubusercontent.com/12829262/230951932-8b8db305-6d54-4b1a-b989-95e5ca602c4f.png)

El resto, tal y como indica en el README.
